### ISSUE TITLE
Setting Playback and DuckOthers does not work

### ISSUE THREAD

**Issue by rpavlovs** [BonnierNews/react-native-audio-session#3]
```js
import * as ReactNativeAudioSession from 'react-native-audio-session'

await ReactNativeAudioSession.default.setCategory(
  ReactNativeAudioSession.AudioCategories.Playback,    
  ReactNativeAudioSession.AudioOptions.DuckOthers
)
```
Errors out with `Error Domain=NSOSStatusErrorDomain Code=-50 "(null)"` which means parameters error according to this issue:
https://stackoverflow.com/questions/1861989/avaudioplayer-initialization-error-code-50

Any idea why this happens?

**Comment by dlindstrm** [comment]
Fixed by https://github.com/BonnierNews/react-native-audio-session/pull/4.

**Comment by mmxdr** [comment]
Still doesn't work. Cannot set DuckOthers with Playback category, others work well.

.currentCategoryOptions() returns 'Unable to get current options'.

"react-native": "0.61.5"
"react-native-audio-session": "0.0.6"
